[package]
name = "invmatrix"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.4.1"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
nalgebra = "0.29"
